### ISSUE TITLE
Received initial value not getting set-> validator says it's null

### ISSUE THREAD

**Issue by VladRoscaDev** [shivanshtalwar0/material_dropdown_formfield#1]
Hello, and thank you for this awesome widget.
I think I have found a bug in it's functionality. The moment i received a value from a provider, it is getting set, it shows on the screen, but when i call the validate method it the value is null.

I think I know why this is happening. It is because the widget if it gets an initial value should also call onChange method. 
I think that this issue is handled by the developer of dropdown_formfield by adding it as a field that you can add.
If there is anymore help i can provide, please do ask.

**Comment by shivanshtalwar0** [comment]
Thanks for bringing this issue to my notice. if you think you can help me fix it you are very welcome just open a pr for the same and I will merge it, otherwise, I might fix it in the coming few days.

**Comment by shivanshtalwar0** [comment]
this bug is fixed now! enjoy!

**Comment by VladRoscaDev** [comment]
Hello, and thank you for the prompt response, I tried it and I still get the same error.

The behavior:
At first the initialValue is null, after that i receive it through ModalRoute.of(context).settings.arguments. Once I received it i call set state and is shows up on the screen. The problem is that the dropdown didn't call onChange once the new value was given.

```dart 
Container(
      padding: const EdgeInsets.all(8.0),
      child: DropDownFormField(
        initialValue: selectedVar,
        inputDecoration: InputDecoration(
          prefixIcon: Icon(Icons.help),
        ),
        innerTextStyle: TextStyle(fontWeight: FontWeight.bold),
        titleText: 'Help',
        hintText: 'Choose a method',
        value: selectedVar,
        onSaved: (value) {
          setState(() {
            selectedVar = value;
          });
        },
        onChanged: (value) {
          setState(() {
            FocusScope.of(context).requestFocus(FocusNode());
            selectedVar = value;
          });
        },
        dataSource: dataSource,
        textField: 'display',
        valueField: 'value',
        validator: (value) {
          if (value == null) {
            return 'This field is required';
          }
          return null;
        },
      ),
    );
```

**Comment by shivanshtalwar0** [comment]
Ahh okay i got you reason why you are facing this problem is because value of selectedVar must  be intialized with empty string or atleast one of the target value otherwise it will fail to work, actually that's not bug that's how cettores initially implemented this functionality try initializing your selectedVar with some value or atleast empty string

**Comment by shivanshtalwar0** [comment]
If it still doesn't work then please attach your complete stateful widget's code so that i can find out more information on the problem

**Comment by VladRoscaDev** [comment]
A big thanks! It is working, my bad, didn't know that I have to initialize it like this. A possible improvement would be to check if it's null and initialize it in the widget.
Have a nice day and keep up the good work!

**Comment by VladRoscaDev** [comment]
It passes the validator issue, but the value is still null. If i manually pick a value it works perfect. Any ideas? On _formKey.currentState.save() the value in onSaved:(value){} the value is null

**Comment by VladRoscaDev** [comment]
I managed to do a workaround, but I feel like this a bad practice and it should not be like this.
```dart 
onSaved: (value) {
          setState(() {
            if (value != null) {
              selectedTransport = value;
            }
          });
        },
```

**Comment by shivanshtalwar0** [comment]
yes in the next release I will add assert when the value of property value is null, about save, I think i haven't added that part of code in next release. I will fix that too!
